defaults: &defaults
  host: localhost
  port: 6379

development:
  <<: *defaults

test:
  <<: *defaults

# set these environment variables on your prod server
production:
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>
  username: <%= ENV['REDIS_USERNAME'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
